### ISSUE TITLE
feat: Make GetConnectionProfile optional

### ISSUE THREAD

**Issue by Pythbit** [dalrrard/ansible-solarwinds-inventory-plugin#15]
# Feature Request

Just wanted to say I appreciate your work on this. We're not fully using Ansible yet, and I was goofing about with my own plugin with... mixed results. I was thinking "there's no way we're the only ones using Orion/NCM as a source!" and was surprised there wasn't one in collections that I could find.

**Describe the Feature Request**

Invoking GetConnectionProfile is really handy, but depending on how much access and trust we want to give to Ansible, it's unhelpful to have the only option be cutting it out of the script.

**Describe Preferred Solution**

Add an additional parameter to the inventory source that allows toggling of this feature.

**Describe Alternatives**

Provide an alternative version with this aspect removed. I could fork and do my own, if that's easier.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by dalrrard** [comment]
I've added a `use_connection_profiles` boolean flag that I think accomplishes what you're wanting. Can you switch to the [add-connection-profile-flag](/dalrrard/ansible-solarwinds-inventory-plugin/tree/add-connection-profile-flag) branch and see if that works?

**Comment by Pythbit** [comment]
Looking at the changes, yeah that's exactly it. Any testing would have to wait for next week, though.

**Comment by Pythbit** [comment]
Hey, maybe it's something on my side, but I'm getting the following errors w/ traceback now when running ansible-inventory --list -vvv:
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute '__dict__'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-inventory", line 128, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.9/site-packages/ansible/cli/inventory.py", line 129, in run
    self.loader, self.inventory, self.vm = self._play_prereqs()
  File "/usr/lib/python3.9/site-packages/ansible/cli/__init__.py", line 476, in _play_prereqs
    inventory = InventoryManager(loader=loader, sources=options['inventory'])
  File "/usr/lib/python3.9/site-packages/ansible/inventory/manager.py", line 167, in __init__
    self.parse_sources(cache=True)
  File "/usr/lib/python3.9/site-packages/ansible/inventory/manager.py", line 225, in parse_sources
    parse = self.parse_source(source, cache=cache)
  File "/usr/lib/python3.9/site-packages/ansible/inventory/manager.py", line 276, in parse_source
    for plugin in self._fetch_inventory_plugins():
  File "/usr/lib/python3.9/site-packages/ansible/inventory/manager.py", line 204, in _fetch_inventory_plugins
    plugin = inventory_loader.get(name)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/loader.py", line 807, in get
    return self.get_with_context(name, *args, **kwargs).object
  File "/usr/lib/python3.9/site-packages/ansible/plugins/loader.py", line 827, in get_with_context
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/loader.py", line 791, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/sw/ansible/network/plugins/solarwinds.py", line 97, in <module>
    class Credentials:
  File "/usr/lib64/python3.9/dataclasses.py", line 1021, in dataclass
    return wrap(cls)
  File "/usr/lib64/python3.9/dataclasses.py", line 1013, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib64/python3.9/dataclasses.py", line 863, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/usr/lib64/python3.9/dataclasses.py", line 863, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/usr/lib64/python3.9/dataclasses.py", line 714, in _get_field
    and _is_type(f.type, cls, typing, typing.ClassVar,
  File "/usr/lib64/python3.9/dataclasses.py", line 660, in _is_type
    ns = sys.modules.get(cls.__module__).__dict__
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dalrrard** [comment]
Sorry for the delay. I got that at some point too, but it was right after I did an in-place upgrade of my OS, so I thought that was the issue. I reinstalled and upgraded Ansible inside of my virtual environment to fix that issue. Maybe it'll work for you? If not, let me know

**Comment by Pythbit** [comment]
Hey, yeah, odd environment issues here, too. All fixed now and works as expected, thanks!

**Comment by dalrrard** [comment]
Awesome! I'll merge these changes and close this out.
